import { Note } from './types';

const welcomeNote: Note = {
    _id: '1',
    title: 'Welcome',
    content: `Discover the features of NoteMarkdown, **your ultimate yet simple markdown editor**.

**[Sign up](/signup)** for free to **save your changes and create new notes**.

*Click the **pencil icon** on the top right corner to start editing this note.*
***

The following table of contents is automatically generated by naming any H2 or H3 (## or ###) "Table of Contents"

## Table of Contents

## Code Syntax Highlighting
NoteMarkdown supports syntax highlighting for various programming languages:

\`\`\`python
# Python example
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

print(factorial(5))
\`\`\`

\`\`\`javascript
// JavaScript example
function fibonacci(n) {
    if (n <= 1) return n;
    return fibonacci(n - 1) + fibonacci(n - 2);
}

console.log(fibonacci(6));
\`\`\`

Isn't that neat?

## Tables
| Project       | Status     |
| ------------- | ---------  |
| NoteMarkdown  | Complete   |
| Next project  | Pending    |

(Markdown source for columns and rows do not need to align)

## Todo Lists
- [ ] Finish the NoteMarkdown project
- [x] Create an example note

## Numbered Lists
1. One
Some text here
2. Two
Some more here
3. Three
And of course some here


## Text Formatting
**Bold**
*Italic*
*Combined*
~~Strike through~~
\`Inline code\`

## Automatic URL linking
https://note-markdown.vercel.app
And with custom labels [NoteMarkdown](https://note-markdown.vercel.app)

## Images
![Image](https://note-markdown.vercel.app/stock.jpeg)

## Quotes
> "Your imagination is the preview of life's coming attractions." - Albert Einstein

## Horizontal lines
***
You can use two for a cool divider
***
NoteMarkdown follows [CommonMark](https://commonmark.org/help/) conventions.

Made with ❤️ by [Lucas](https://x.com/LucasCodes)
`
};

export default welcomeNote;